### ISSUE TITLE
Support for greater number of virtual desktops

### ISSUE THREAD

**Issue by gikari** [tcorreabr/Parachute#10]
**Setup:** 
Create a lot of  virtual desktops (for example 13)

**Expected:** 
Top bar shows the number of virtual desktops it can fit, but the rest are available via scrolling the top bar or/and by hovering the cursor on the edges of top bar.

**Actual:**
 Only some of the desktops are shown and there is no top bar scrolling.
![image](https://user-images.githubusercontent.com/14205339/77631503-923aae80-6f44-11ea-9a02-7a1e2e243afd.png)

**Comment by MichaelTunnell** [comment]
It depends on the size of the monitor, so far 6 Desktops looks great but at 7 it becomes cutoff and then 8 or more is not usable for the rest.

**Comment by tcorreabr** [comment]
Are you using the develop branch? I've fixed this issue there.

**Comment by MichaelTunnell** [comment]
I just used whatever came with the install from the KDE Store. I assume that is a standard release version but I am not sure when the dev version updates there.
