### ISSUE TITLE
Notification thumbnails

### ISSUE THREAD

**Issue by divinae** [tcorreabr/Parachute#11]
Notifications are visible as window.
![Screenshot_20200326_132045](https://user-images.githubusercontent.com/49128105/77646543-0422f000-6f65-11ea-8374-1b9c7b42fca1.png)

**Comment by tcorreabr** [comment]
I think this may be a bug for some, but a feature for others. Maybe it will become an config option.

**Comment by divinae** [comment]
Firefox Picture in Picture window is visible too.
![Screenshot_20200331_125321](https://user-images.githubusercontent.com/49128105/78018736-b6d0c500-734e-11ea-820b-daa28cadea21.png)

**Comment by divinae** [comment]
I'm using:
`KWinComponents.ClientModel.SkipPagerExclusion | KWinComponents.ClientModel.SwitchSwitcherExclusion`

**Comment by tcorreabr** [comment]
Ok. As soon as the config dialog is implemented this will become an option.
