### ISSUE TITLE
With Virtual Desktop Bar, parachute keyboard shortcut ineffective until kwin restart or dynamic desktop operations

### ISSUE THREAD

**Issue by AndydeCleyre** [tcorreabr/Parachute#14]
Each time I boot up and login, the keyboard shortcut (`ctrl`+`alt`+`w`) has no effect, until I run `kwin_x11 --replace`, then it's fine. The setting appears correct throughout, in the Global Shortcuts KCM.

I wonder it it's some timing issue during session startup. I am also using latte dock and virtual desktop bar (which I know causes other issues for this script), so I can play around with disabling those later.

Arch Linux
kwin & plasma-desktop `5.18.4.1`
kwin-scripts-parachute `0.5.1`

Thanks again for the great work!

**Comment by AndydeCleyre** [comment]
Alright, looks like it's another problem with Virtual Desktop Bar (`r422.25ec1c0`), without which the problem doesn't present, and with, I can also get the shortcut working (without restarting kwin) by moving windows across desktops enough to get new desktops created and removed.

Maybe @wsdfhjxc has an idea here.

![Screenshot_20200404_120859](https://user-images.githubusercontent.com/1787385/78455871-a2ead300-766e-11ea-9d0a-d1e515794aa3.png)
![Screenshot_20200404_120840](https://user-images.githubusercontent.com/1787385/78455872-a3836980-766e-11ea-8299-0d04d2ae75a8.png)

**Comment by wsdfhjxc** [comment]
Ok, while I can see the other issue regarding handling desktops being on my side, in case of this particular issue, I have no idea why it's happening, as there is nothing that could interfere regarding keyboard shortcuts. Can you tell me what action is assigned to that keyboard shortcut in your setup?

**Comment by AndydeCleyre** [comment]
@wsdfhjxc It's just the parachute default, corresponding to this line in `kglobalshortcutsrc`:

```ini
Parachute=Ctrl+Alt+W,none,Parachute
```

**Comment by AndydeCleyre** [comment]
@wsdfhjxc This problem occurs if and only if I have automatic removal enabled.

`plasma5-applets-virtual-desktop-bar-git r432.b144b08`

**Comment by tcorreabr** [comment]
I'm closing this one just for organization. But feel free to add any relevant information.

**Comment by AndydeCleyre** [comment]
Should further discussion move to another issue; what's the new organization?

What more information would be relevant?

**Comment by tcorreabr** [comment]
> @wsdfhjxc This problem occurs if and only if I have automatic removal enabled.
> 
> `plasma5-applets-virtual-desktop-bar-git r432.b144b08`

Do you think it would be a good idea to include this information as a note in the README file?

**Comment by AndydeCleyre** [comment]
As far as I know @wsdfhjxc doesn't believe it can be related to that applet, but I don't know that they've tested to try to replicate.

**Comment by wsdfhjxc** [comment]
It's not that I don't believe it. I just have no idea why there is a correlation and how to resolve the issue.
