### ISSUE TITLE
GTK windows without margins

### ISSUE THREAD

**Issue by tcorreabr** [tcorreabr/Parachute#17]
As mentioned by @koma111 on #16, GTK window thumbnails have no margins and this behavior is defined by Kwin component responsible for painting them. Maybe I can add margins if I can find out if a particular thumbnail is from a GTK window. Although this is not a very elegant solution.

**Comment by zzag** [comment]
When I introduced support for client-side decorated clients, my thinking was that neither scripts nor effects have to be concerned about client-side or server-side decorations. It's quite possible that I overlooked a thing or two in the scene responsible for drawing window thumbnails.

**Comment by tcorreabr** [comment]
Got it. Well, I'm thinking of using the client.noBorder property to add margins via QML. Apparently this will work well as a temporary solution.
