### ISSUE TITLE
Parachute doesn't respect activities

### ISSUE THREAD

**Issue by andrewc910** [tcorreabr/Parachute#19]
Make a second 'Activity' in the kde settings. On the same virtual desktop index, open an application on each activity. Open parachute. Parachute aggregates all applications across all activities.

**Comment by tcorreabr** [comment]
@zzag just fixed it: https://phabricator.kde.org/D28827

I'll leave this issue open until a new version of KWin is published with the patch.

**Comment by alexjp** [comment]
I am happy to report that using 5.19 git packages makes this fixed !
In my ( albeit short ) testing, windows from one activity don't appear on others.

**Comment by alexjp** [comment]
ps: its actually pretty slick to change activities while Parachute is activated :)

**Comment by zzag** [comment]
@alexjp Yes, the fix is in 5.19, it probably needs to be backported to 5.18...
