### ISSUE TITLE
Scroll to change desktop

### ISSUE THREAD

**Issue by divinae** [tcorreabr/Parachute#2]
Could you add option to change desktop with mouse scroll?

**Comment by tcorreabr** [comment]
Apparently, yes. I'll investigate further.

**Comment by tcorreabr** [comment]
Wheel scroll will not work on the desktops bar, because it can now be used to scroll on it in the case of many desktops (issue # 10). On the rest of the screen it will work.

**Comment by divinae** [comment]
Thank you - it's working.
Unfortunately for my touchpad it's not usable - it's really hard to scroll only one desktop.
