### ISSUE TITLE
Suggestion: Super+Ctrl+D to "deploy Parachute"

### ISSUE THREAD

**Issue by MichaelTunnell** [tcorreabr/Parachute#20]
I suggest using the Super+Ctrl+D (Meta+Ctrl+D) shortcut to "deploy Parachute" ( :sunglasses: ) because I think it makes sense and is also a more comfortable shortcut to do. Additional reason is that this is the default shortcut for virtual desktops overlay in Windows so anyone who switches from that would already know how to use this. :+1: 

This wont conflict with any KDE Plasma shortcuts.

**Comment by tcorreabr** [comment]
I agree with you. I may have to alert the user with big red letters somewhere in the new version. Does the current shortcut conflict with any Plasma shortcuts? I don't remember seeing that.

**Comment by MichaelTunnell** [comment]
No, the current Ctrl+Alt+W does not conflict with anything but I just think that Ctrl+Meta+D fits a bit better. It could stay as is overall if you want.

**Comment by koma111** [comment]
If it integrates with KWin properly, (as in the user being able to select a custom shortcut through System Settings > Shortcuts), both can be set, as KDE has the option of primary AND secondary shortcuts.
So you can have your cake and eat it too.

**Comment by tcorreabr** [comment]
I just realized that I can change the shortcut without impacting existing users. Anyone who already has Parachute installed will continue to use Ctrl+Alt+W even after installing new versions. So I think the problem is not that big.

**Comment by tcorreabr** [comment]
@MichaelTunnell, I went to make sure and it seems that in Windows the Super+Ctrl+D shortcut is for adding a desktop, right?
