### ISSUE TITLE
keyboard navigation not working when opening parachute with qdbus command

### ISSUE THREAD

**Issue by gobonja** [tcorreabr/Parachute#21]
When opening parachute with `qdbus org.kde.kglobalaccel /component/kwin invokeShortcut Parachute` focus stays on last active window and that window recieves keyboard events.
This issue doesn't occur when opening parachute with global keyboard shortcut (e.g. Ctrl+Meta+D)

Steps to reproduce:
1. open terminal or alt-tab opened terminal
2. move mouse so none of the applications gets under mouse pointer in paraschute
3. run `qdbus org.kde.kglobalaccel /component/kwin invokeShortcut Parachute`
4. try selecting application with keyboard

I face this problem a lot since I use fusuma gestures and Meta key for opening parachute.
Here is also quick recording of bug: 
[bug-preview.zip](https://github.com/tcorreabr/Parachute/files/4495299/bug-preview.zip)

**Comment by tcorreabr** [comment]
Strange. I can reproduce this by running the qdbus command on terminal. But when the same command is executed by easystroke everything works normally. 🤔

**Comment by gobonja** [comment]
I just tried with easystroke, same issue occures but only if gesture is not initiated on maximized window. But if initiated on maximized still cannot switch windows with keyboard.  
[easystroke.zip](https://github.com/tcorreabr/Parachute/files/4496835/easystroke.zip)

**Comment by tcorreabr** [comment]
As if that weren't strange enough.
