### ISSUE TITLE
Doesn't seem to work on Kubuntu 20.04

### ISSUE THREAD

**Issue by AlekEagle** [tcorreabr/Parachute#26]
I can't seem to trigger it via the global shortcut or via the command, this is the first time I've used the script, so I've never seen it in action.
System info:
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-26-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-2520M CPU @ 2.50GHz
Memory: 15.6 GiB of RAM

**Comment by tcorreabr** [comment]
Did you install using the commands mentioned in the README file or via Kde Store?

Did you activate the script in the KWin Scripts window?

**Comment by AlekEagle** [comment]
yes and yes, ill try it again, but so far ive had no luck

**Comment by AlekEagle** [comment]
it doesn't show in global shortcuts as a KWin Script either

**Comment by ascesh** [comment]
Hi !

having a similar issue.

tried installing and uninstalling multiple times from
https://store.kde.org/p/1370195/ 
and 
also kpackagetool5

the extension is enabled in kwin scipts
I have tiling windows also enabled .. in a suspicion tried disabling tiling windows , but still parachute didn't start

tried strating it with using the ctrl+super+w and ctrl+alt+w and qdbus org.kde.kglobalaccel /component/kwin , but none seem to work 


where can I find more logs ? and how do I debug this further myself ?


My setup :

Operating System: Fedora 32
KDE Plasma Version: 5.18.3
KDE Frameworks Version: 5.68.0
Qt Version: 5.13.2
Kernel Version: 5.6.6-300.fc32.x86_64
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-8650U CPU @ 1.90GHz
Memory: 15.5 GiB of RAM

**Comment by smessina0076** [comment]
On Kubuntu 20.04
I solved this issue changing the version of QtQuick in import block for the files:

- ClientComponent.qml  
- DesktopComponent.qml  
- Enums.qml  main.qml  
- ScreenComponent.qml

From
import QtQuick 2.14
import QtQuick.Controls 2.14
import QtQuick.Layouts 1.14

To 
import QtQuick 2.12
import QtQuick.Controls 2.12
import QtQuick.Layouts 1.12

Moreover I had to comment the code

` /*  WheelHandler {
        property int wheelDelta: 0

        onWheel: wheelDelta += event.angleDelta.y;

        onActiveChanged: {
            if (active === true) return;

            if (wheelDelta >= 120 || wheelDelta <= -120) {
                wheelDelta > 0 ? workspace.currentDesktop-- : workspace.currentDesktop++;
                wheelDelta = 0;
            }
        }
    }*/`

Because a new exception was raised: ScreenComponent.qml:156:5: WheelHandler is not a type.

I hope this can help.

**Comment by tcorreabr** [comment]
I completely forgot about the Qt versions. Thanks @smessina0076 for sharing the solution to this issue.

For Parachute to support the .12 version the WheelHandler would have to be created dynamically only if the installed Qt version is >= .14.

I'll research if we can have access to the installed Qt version from QML.

**Comment by AlekEagle** [comment]
I did this, but alas no luck, is there anyway I can debug it and look for any other issues?

**Comment by tcorreabr** [comment]
Debugging a KWin script is not one of the most enjoyable tasks. I even managed to use Qml debugger in Qt Creator up to a certain point in the project. Currently I'm debugging the code with console.log function.

Have you tested it using the develop branch? (git switch develop)
