### ISSUE TITLE
Issue after rebooting/logging out and back in?

### ISSUE THREAD

**Issue by Dashon1** [tcorreabr/Parachute#28]
Hey great script it functions as expected and everything, however I seem to be having a problem after logging out and back in or otherwise restarting my computer in some way. If I do either of the aforementioned things. Kde plasma becomes extremely slow and unresponsive until i disable this script. Disabling and reenabling the script makes everything work as expected and it is all smooth sailing. However I have to do this anytime I want to end the current session. Any ideas on this?

Currently on openSuse Tumbleweed all packages up to date. (Which may be part of the problem)
Plasma 5.18.5
Qt version 5.14.1

**Comment by Dashon1** [comment]
Also wanted to add it seems to also occur when changing application styles.

**Comment by Dashon1** [comment]
Narrowed it down a bit further. The slow down occurs if you use the show desktop grid effect after rebooting or logging out and back in while the Parachute script is enabled. Disabling this script and re-enabling it allows for both of these effects to be used in conjunction. I still don't know what is causing this to happen though.

**Comment by tcorreabr** [comment]
Strange, I'm not having those slow downs here.

It would be nice if you could test these issues on another machine, with another distribution. If you can't, we'll have to wait for more feedback from users.

**Comment by Dashon1** [comment]
I'll try it out in a few virtual machines and see how things go.

**Comment by Dashon1** [comment]
Sorry it took a while. Tried it out in manjaro. Looks like you are right it didn't happen there. Some differences that I noticed however was that the version in manjaro did not show the background where as it does show the background in openSuse Tumbleweed. Another thing that may be worth mentioning is that I am calling Parachute via qdbus. I know that this problem occurs when I enable parachute. Is their something I can do to further debug this?

**Comment by Dashon1** [comment]
I should also add that after the latest update to tumbleweed. This problem occurs after a few minutes of use regardless of whether or not I shut down.

**Comment by Dashon1** [comment]
qdbus doesn't seem to be the issue either. I'm on intel integrated graphics as well, so I didn't expect compositor settings to do much. Tried messing around with them anyways, but those didn't work either. Definitely an openSuse TW problem, I just can't seem to pinpoint it.

**Comment by tcorreabr** [comment]
Are you using Intel video driver on both systems?

**Comment by Dashon1** [comment]
I tested manjaro in a virtual machine, so yes I guess?

**Comment by tcorreabr** [comment]
Well, I would try to check if the correct x11 driver is installed and properly configured on your opensuse tw.

**Comment by Dashon1** [comment]
Took a minute and some research, but everything seems to be in line on the driver side of things as well. I wasn't expecting issues on intel graphics anyways. Is there some dependency I might be missing on openSuse?

**Comment by tcorreabr** [comment]
I don't think so. The only dependencies are: Qt, Plasma and KWin.

**Comment by Dashon1** [comment]
Well, I'll let it sit for a minute and see if a few updates fix the issue. It may be a bug in some component of my system.

**Comment by Dashon1** [comment]
After the latest update to tumbleweed this issue seems to have solved itself. Thanks for your time.

**Comment by tcorreabr** [comment]
Cool. No problem.
