### ISSUE TITLE
Desktop wallpapers are not shown

### ISSUE THREAD

**Issue by alexjp** [tcorreabr/Parachute#3]
Hi,

When on wayland, all the wallpapers are just dark gray color ( #333333 if not mistaken )

Thanks !

**Comment by tcorreabr** [comment]
This issue doesn't happen only on Wayland. Actually, the code to find out which window is the desktop (to show the wallpapers) is not very good, currently. I'll see with the kwin developers if this can be improved.

**Comment by MichaelTunnell** [comment]
I have experienced a similar problem but I was able to do a workaround simply by activating the Configure Desktop dialog window, not even change anything, just open it and close it. This is not a solution of course but might help narrow it down hopefully.

Here is my experience with what it is doing and me demonstrating the Configure Desktop workaround: https://youtu.be/-ktu5wS-v_c

Here is the next day when I realized it happened again but this time the bottom 3rd of the effect is cutoff displaying the normal desktop behind it. https://youtu.be/MVRLHs0_-p4

**Comment by tcorreabr** [comment]
It got a little better with a change (https://github.com/tcorreabr/Parachute/commit/b6788dd2b2e7eddd2f45d0b96d8d40fc2aef3d74) I made in develop branch, but it's still not ideal.

**Comment by tcorreabr** [comment]
Are you using Wayland? I think the cutoff is a "Wayland only" issue described here #4.

**Comment by MichaelTunnell** [comment]
I am not using Wayland, no. I am still using X and I was able to workaround the issue simply by disabling and reenabling the script in System Settings.

**Comment by tcorreabr** [comment]
Well, then it may be something related to multiple screens. I am limited to the notebook screen in this covid quarantine.

**Comment by alexjp** [comment]
> Well, then it may be something related to multiple screens. I am limited to the notebook screen in this covid quarantine.

I was thinking that myself, but I don't see that offset on X11 session ( with multiple screens )

**Comment by divinae** [comment]
I see that cutoff when I switch from laptop monitor (16x9) to external one (16x10)

**Comment by MichaelTunnell** [comment]
My multiple monitor setup is pretty weird so maybe that could be a factor.

Left to Right:
(1) 1920x1080 - 16:9 in Vertical orientation (TN)
(1) 1920x1200 - 16:10 (IPS)
(1) 1920x1080 - 16:9 (TN)

This could be why I am dealing with this because the layout of my setup is all kinds of funky

**Comment by tcorreabr** [comment]
I detected a cutoff when I turned the screen 90 degrees via Plasma settings. I already fixed this in the develop branch, but I'm still not sure that this is the error mentioned by you. Time will tell.

**Comment by MichaelTunnell** [comment]
I will test it out in the next release for sure to let you know. I am also ok with testing the dev version as well after I get this weeks work (video production) done. :+1: :sunglasses:

**Comment by tcorreabr** [comment]
New version released. I hope those cutoffs don't show up in the video again.

**Comment by MichaelTunnell** [comment]
unfortunately based on my testing, the cutoffs are still happening

btw I mentioned Parachute on my Destination Linux podcast :sunglasses:

**Comment by tcorreabr** [comment]
> unfortunately based on my testing, the cutoffs are still happening

Ok, I'll try to figure out what's causing this.

> btw I mentioned Parachute on my Destination Linux podcast sunglasses

Cool. I'll watch.
