### ISSUE TITLE
Info on README.md about using it with meta key 

### ISSUE THREAD

**Issue by alexjp** [tcorreabr/Parachute#30]
Hi,

I am using metakey only to invoke Parachute.
this can be done with:

`kwriteconfig5 --file ~/.config/kwinrc --group ModifierOnlyShortcuts --key Meta "org.kde.kglobalaccel,/component/kwin,org.kde.kglobalaccel.Component,invokeShortcut,Parachute"`
and
`qdbus-qt5 org.kde.KWin /KWin reconfigure` (qdbus-qt5 may be opensuse only, may be qdbus in other distros)

Maybe this can be included on the README.md ?

Thanks !

**Comment by tcorreabr** [comment]
Yes, I'll do it. Thanks.

**Comment by basicJavaCoder** [comment]
How would I unbind parachute from the meta key when I want to revert the commands above?

**Comment by koma111** [comment]
I think you can just invoke the same commands but instead of `"org.kde.kglobalaccel,/component/kwin,org.kde.kglobalaccel.Component,invokeShortcut,Parachute"` write `""`... Not sure though

**Comment by basicJavaCoder** [comment]
That method did not work.

But manually editing that `~/.config/kwinrc` file and deleting the line for binding the key under ModifierOnlyShortcuts did actually work! 
Thanks for the suggestion :D

**Comment by tobealive** [comment]
For me this one works for some minutes after booting into the system then it stops to work. Does anyone has an idea to solve this issue? Kind regards

**Comment by tobealive** [comment]
Okay fixed / worked around this issue. 
Using ksuperkey and assiged the standard parachute keyboarshortcuts to open parachute with meta key only.

`ksuperkey -e 'Control_L=Escape;Super_L=Alt_L|F2'`

**Comment by kalexm** [comment]
It is not working for me. I tried Meta+D, no response, I tried to remap it to only meta, not showing, I tried ksuperkey, not working either. Even when sending a qdbus signal directly, not showing. How to start finding the issue now? Any log to investigate?
BTW, Parachute is showing in the kwin scripts..
