### ISSUE TITLE
F5 doesn't refresh settings.

### ISSUE THREAD

**Issue by baduhai** [tcorreabr/Parachute#32]
As per release notes

> Config dialog to change some preferences (you have to press F5 with the script activated for the changes to take effect).

Pressing F5 doesn't update Parachute to use new settings.

Edit: In fact, settings are not taking effect. None of the settings display any change after logout/login. Please provide some info as to how I can help debugging this issue.

**Comment by tcorreabr** [comment]
Can you post the result of the command "grep -C 3 Parachute ~/.config/kwinrc"?

To see the output messages from qml/javascript in a terminal you have to run "kwin_x11 --replace &". Currently I use javascript's console.log function (or qml's print function) to debug the code.

**Comment by baduhai** [comment]
> grep -C 3 Parachute ~/.config/kwinrc

```
LongitudeAuto=-9.1863

[Plugins]
ParachuteEnabled=true
coverswitchEnabled=true
desktopchangeosdEnabled=true
dynamic_workspacesEnabled=false
--
windowgeometryEnabled=false
wobblywindowsEnabled=true

[Script-Parachute]
showDesktopShadows=true
showNotificationWindows=false
showWindowTitles=false
```

**Comment by tcorreabr** [comment]
Looks like your kwinrc file is fine. At those times not using a real debugger really gets in the way.

I forgot to mention this in the release notes, but F5 only works when the Parachute window is visible on the screen.

What is your version of Plasma and Qt?

> Running `kwin_x11 --replace &` displays output for many kwin scripts, but nothing about parachute.

You have to use the print function on the code to see some output from parachute.

**Comment by AndydeCleyre** [comment]
Just adding my experience here that hitting `F5` while in parachute's view does indeed refresh the settings for me, on Arch, with current release installed via AUR. I tested by enabling the desktop shadows option.

@baduhai distro? software versions?

**Comment by baduhai** [comment]
I'm on arch and have the aur package installed. I'm not entirely sure why, but uninstalling and reinstalling the package has fixed my problems. Maybe it was a problem caused by the upgrade? I guess the issue can be closed?
