### ISSUE TITLE
[Feature] to immediately open on the clicked application 

### ISSUE THREAD

**Issue by Da-Viper** [tcorreabr/Parachute#33]
For example if your enable parachute the desktop are shown. if you want to switch to a different application in another desktop.you will have to click on the desktop and then the application. 

it would be better instead of that, once you clicked on the application in the other desktop it immediately goes to the application 

video explaining what i mean https://streamable.com/0a1c72

**Comment by Da-Viper** [comment]
If you want to go to another desktop you just click on the area that has a desktop

**Comment by AndydeCleyre** [comment]
What about double-clicking on one of the tiny window thumbnails, within one of the mini desktops at the top, to go directly to that window and exit parachute view? 

And double-clicking on a non-window space to go to that desktop and exit parachute view?

**Comment by tcorreabr** [comment]
Clicking on the current desktop is currently not associated with any action, so I think it could be used to activate a window or to exit Parachute view, depending on the case. In practice, double clicks should work with this solution. What do you think?
