### ISSUE TITLE
No window preview, only icons

### ISSUE THREAD

**Issue by long21wt** [tcorreabr/Parachute#35]
![Screenshot_20200603_022820](https://user-images.githubusercontent.com/46249208/83582494-efa13c00-a541-11ea-9082-4d87f7be1abc.png)
So basically i don't have window preview and only icons left. This weird issues doesn't happen when i tested in a wm.

**Specification**
Operating System: Manjaro Linux (Unstable Branch)
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2

btw thanks for your jobs, it makes me want to use KDE back. Before this KDE with 720p resolution was simply unusable because of the annoying grid overview.

**Comment by long21wt** [comment]
i forgot to mention, i got the script from kde store.

**Comment by long21wt** [comment]
OMG i didn't know that i accidentally disable animations. It can be closed now. Hopefully someone who has the same issue can find it directly from github.

**Comment by 5c0rp10** [comment]
I have the same issue on manjaro. How do I fix this?
