### ISSUE TITLE
[Feature Request] Search for window

### ISSUE THREAD

**Issue by joaopauloalbq** [tcorreabr/Parachute#37]
Search for window when typing like Present Window effect.

![HD](https://user-images.githubusercontent.com/9905202/84605314-c4d4b300-ae72-11ea-901b-fc7e7dbe5d63.gif)

**Comment by ikeofkc** [comment]
I think search krunner upon typing like would be more flexible and useful, I think you can switch windows with it even. There is a feature request for that currently

**Comment by tcorreabr** [comment]
I agree with @ikeofkc. I was thinking of using the alphabet keys to activate krunner (#43).

**Comment by AndydeCleyre** [comment]
While krunner can do more things than a dedicated window filter, the window filtering experience of Plasma's Present Windows effect is *leagues* better than doing so with krunner, because you get to see previews of the matching windows, and they get bigger as the match set diminishes.

**Comment by tcorreabr** [comment]
Good point. You reminded me that the main goal of Parachute is to be a window switcher and not a launcher. It seems that we will have a turnaround here.
