### ISSUE TITLE
Animation is kinda brutal and not elegant

### ISSUE THREAD

**Issue by michaldybczak** [tcorreabr/Parachute#38]
This is about cosmetics but currently the animation is super quick, a bit too quick. Maybe because of that it lacks smoothness and elegance. Or maybe it's not about the speed but the animation itself?

The default overview is also quick and yet smooth, but parachute's counterpart feels raw. Maybe the best way to describe it - it lacks smoothness of the usual overview animation.

If you compare those two animations one after another, they have very different look.

Any idea if that could be improved?

**Comment by tcorreabr** [comment]
I've already tried some tweaks on animations, especially regarding duration and easing types. Please read https://phabricator.kde.org/T13224 for more info on this.

**Comment by michaldybczak** [comment]
OK, then there is no need for this issue.

The effect is so bad and all animations so clunky that it looks really, terrible at the moment.
Also, I often get grey/black or whitish background instead the wallpaper, if there are more open windows in the background. Not sure why.

![Screenshot_20200620_120837](https://user-images.githubusercontent.com/10132958/85199308-cbd64800-b2ee-11ea-85ae-ccc91a50f681.jpg)


The idea  for this is script is awesome and hopefully this will be integrated into Plasma, but at the moment it looks raw and appalling, but I assume this is only a temporal state.

Thanks for letting me know about the discussion. You can close the issue.
