### ISSUE TITLE
Restarting script without restarting kWin

### ISSUE THREAD

**Issue by anesuc** [tcorreabr/Parachute#39]
Hi,

I was wondering is there any possibility to be able to restart the script without restarting kWin?

Thanks

**Comment by tcorreabr** [comment]
You can uncheck and re-check the script in the KWin Scripts window. Or call dbus methods for unloadScript and loadScript.

**Comment by anesuc** [comment]
@tcorreabr Thanks for the response. I am looking for a way to do it programmatically, so the dbus way is the way to go. Do you have an idea of how to go about this? I've been looking online and I am yet to find a solution to this. Unless if you mean completely uninstall and then re-install?

**Comment by anesuc** [comment]
I figured it out. Thanks for the help anyway. For anyone looking for this here:

`kwriteconfig5 --file ~/.config/kwinrc --group Plugins  --key ParachuteEnabled false`
`qdbus org.kde.KWin /KWin reconfigure`
Then change it to true and reconfigure again
