### ISSUE TITLE
Request: Option for desktop bar to appear at the bottom of the screen, rather than the top

### ISSUE THREAD

**Issue by AndydeCleyre** [tcorreabr/Parachute#40]
I keep my desktop pager and task manager widgets on a bottom panel, so I associate related operations with that area of the screen. If Parachute could also display at the bottom, it would be a smoother and more focused target for my attention when using it, rather than having my eyes jump from the bottom to the top and back, when doing desktop and task operations.

Thanks for your continued work on this beautiful project.

**Comment by tcorreabr** [comment]
I was working on that this week. :)

Already with some progress on develop branch (https://github.com/tcorreabr/Parachute/commit/49695ff5dd8e5e62164310a3c11dfa94cc5ff737).
