### ISSUE TITLE
window previews missing

### ISSUE THREAD

**Issue by cast-away** [tcorreabr/Parachute#41]
Hi,

I love the idea of this kwin script but for some reason there is no preview of any of the open windows on my end. See screenshots below.  Windows can still be selected, and even moved to other desktops. 
System information below, any hints?

Operating System: Kubuntu 19.10
KDE Plasma Version: 5.16.5
KDE Frameworks Version: 5.62.0
Qt Version: 5.12.4
Kernel Version: 5.3.0-61-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-5300U CPU @ 2.30GHz
Memory: 15.5 GiB of RAM

![Parachute_Screenshot_20200628_194219](https://user-images.githubusercontent.com/8208567/85956003-51ef3000-b97a-11ea-843a-7c59b98b490b.png)
![Parachute_20200628_194419](https://user-images.githubusercontent.com/8208567/85956001-50be0300-b97a-11ea-9026-9e1a1c396c18.png)

**Comment by tcorreabr** [comment]
Sorry, but I only tested on Plasma 5.18 or higher. Probably the error is related to that.

**Comment by cast-away** [comment]
it is, upgraded to 5.18 and it now works great, thank you for such an amazing script!
