### ISSUE TITLE
Activities and Wallpapers goal

### ISSUE THREAD

**Issue by psifidotos** [tcorreabr/Parachute#42]
I really find this project interesting.
I can really understand why Activities support is not possible yet in your project.
There are plenty of projects that are influenced by Plasma missing feature to not provide a Wallpapers model solution or something similar that would give the option to pagers, kwin overviews, activity manager etc. to provide a proper visual for Activities.

As a middle ground solution I have proposed: https://phabricator.kde.org/T13037

I 'd really like your thoughts in the matter. Such solution could at least give you Live Wallpapers model/data that could be used. For current Activity, the Desktop window could be used but for the rest Activities that are running but are not active the previous solution could provide you their Wallpaper Live Preview (without their widgets layer)

**Comment by tcorreabr** [comment]
I thought it best to answer there.

I don't know if you had the opportunity but we also discussed about it in issue #29.
