### ISSUE TITLE
When the configuration dialog is installed, I cannot start any programs from Application Launcher

### ISSUE THREAD

**Issue by d86leader** [tcorreabr/Parachute#45]
A really weird interaction I know. After I installed the symlink like it says in the readme, and after I relogged-in to the desktop session, I was no longer able to launch any programs from the default launching applet.
I'm running Plasma 5.19.3, Kde frameworks 5.72.0, Qt 5.15.0

Also when I was testing what was causing it, I first disabled parachute and relogged-in, then I removed the symlink and relogged-in, and my plasma went mad: kwin would not start, panels didn't appear, and I couldn't log out or even reboot.

**Comment by tcorreabr** [comment]
Pretty weird indeed. If you get any further information on this, please post here.
