### ISSUE TITLE
[Feature Request] Use hjkl to navigate through windows.

### ISSUE THREAD

**Issue by 20manas** [tcorreabr/Parachute#46]
It'll be a great addition and will allow extremely fast window switching. This is something missing from the Present Windows effect. Adding "hjkl" navigation will allow a really good window switching workflow.

I see that there are two issues, one of which is a feature request for Present Windows' filter effect and the other is for searching in Krunner. Perhaps it can be something like this:

1. Press "f" and start typing to filter windows
2. Press "s" and start typing to search in Krunner
3. Use "hjkl" to navigate windows

Just my thoughts. 🙂

**Comment by tcorreabr** [comment]
I was thinking of using the alphabet keys to activate krunner (#43).
