### ISSUE TITLE
Option to Not Immediately switch to the desktop where you moved the application.

### ISSUE THREAD

**Issue by Dashon1** [tcorreabr/Parachute#49]
For example, I move a window to a different desktop. If the current desktop is empty it will switch to the desktop that I previously moved an application to. Whereas, what I would like to happen is to be able to continue using the current desktop an open a new application.

**Comment by tcorreabr** [comment]
I cannot reproduce this issue. If you can, test if this keeps happening in version 0.9.0 and post here please.

**Comment by Dashon1** [comment]
It was indeed fixed in version 0.9.0. Thanks for all you hard work.
