### ISSUE TITLE
Panel/Bar appearing when change virtual desktop

### ISSUE THREAD

**Issue by DenysMb** [tcorreabr/Parachute#55]
Hi. When we change the virtual desktop, the plasma panel appears (in my case, in top. because I uses it there).
It would be nice if the panel don't appear in this cases. When the parachute is set to top, it appears in front of parachute.
The same happens with someone with the parachute configured to bottom with panel bottom.
PS: The firefox microphone indicator have nothing to do with that.

![image](https://user-images.githubusercontent.com/33737137/95202289-7e0b2000-07b7-11eb-95d4-80b34555e48e.png)

![image](https://im7.ezgif.com/tmp/ezgif-7-cb15a92e78c9.gif)

**Comment by Shubkush** [comment]
Hey, this issue can be solved by enabling Sliding docks under Settings > Workspace Behavior > Desktop Effects > Slide (Under Virtual Desktop Switching Animation)
