### ISSUE TITLE
Is possible to set a option to add more virtual desktop directly from parachute?

### ISSUE THREAD

**Issue by DenysMb** [tcorreabr/Parachute#56]
Like the title says: Is possible to set a option to add more virtual desktop directly from parachute?
Something like the plus button in Deepin Linux virtual desktop overview.

![image](https://i.ytimg.com/vi/dI8RfU_9P3g/maxresdefault.jpg)

![image](https://user-images.githubusercontent.com/33737137/95204375-65503980-07ba-11eb-9a20-cbc9ce78fb2f.png)

**Comment by AndydeCleyre** [comment]
FWIW, [virtual desktop bar](https://github.com/wsdfhjxc/virtual-desktop-bar) provides global shortcut actions for adding and removing desktops, but the interaction with parachute is not ideal.

I hope to eventually reconcile the features I enjoy from each of these plasmoids.

**Comment by f-fouad** [comment]
Actually it does work if you enable the option "Show buttons to add/remove virtual desktops" in the "Grid desktop" desktop effect. (See attached screenshot)
By the way, the "+" sign to add desktops is there but the icon is not visible.

![Screenshot_20201205_125732](https://user-images.githubusercontent.com/6176575/101241845-0e071080-36fa-11eb-8581-878730d53f5f.png)
