### ISSUE TITLE
Using the script lots of times causes kwin to crash

### ISSUE THREAD

**Issue by alexjp** [tcorreabr/Parachute#6]
Hi,

When using the kwin script on wayland, if using some 5 or 10 times, kwin wayland crashes.
I will try to get more info as to why this happens with wayland debug.

Thanks !

**Comment by tcorreabr** [comment]
I think this is because of the background blur. I implemented the use of blur recently and apparently haven't tested it enough.

**Comment by alexjp** [comment]
I will test it without blur then, disabling blur on kwin should be enough ?

**Comment by tcorreabr** [comment]
No, it's a internal (QML) blur. But I tested now without it and the problem persist.

**Comment by tcorreabr** [comment]
I found out what was causing the Kwin crash. It was the code that tried to show the desktop backgrounds at startup. So, for now we have to click on an empty desktop to show the backgrounds. It's a annoying behavior but better than being the cause of a crash. I'll see with the devs of Kwin if we can improve the way of discovering the desktop windows to be able to show the backgrounds correctly.

**Comment by trmdi** [comment]
This seems a workaround and shouldn't be closed until a real fix is found right?
