### ISSUE TITLE
Choppy animations

### ISSUE THREAD

**Issue by raftelo** [tcorreabr/Parachute#63]
Thanks for this beautiful KWin script, I love it!

I'm wondering if the performance can be improved, the animation always looks choppy even if I change the "Scale method" and disable the blur effect, I even tried it on a fresh install. The default grid effect, by contrast, is pretty fast. The following video shows both Parachute/grid animation https://www.youtube.com/watch?v=_GRI_rS9RT0

**Comment by tcorreabr** [comment]
I rewrote a lot of the code to improve the performance of the animations in the next version and I think we will have a visible gain in this aspect.

**Comment by barolo** [comment]
I would like to add that any transparencies/blurs in your window or app decorations will have impact on the smoothness
