### ISSUE TITLE
[Feature Request] Enter key for leaving Parachute on current virtual desktop

### ISSUE THREAD

**Issue by bollian** [tcorreabr/Parachute#66]
I like being able to navigate through desktops using only my keyboard. For example, with how I've configured my hotkeys, I'll

1. Launch Parachute (Ctrl+Super+Up)
2. Go one desktop to the right (Ctrl+Super+Right)
3. Exit Parachute (Ctrl+Super+Up, or Enter if a window is focused)

My request is about this last step. It would be nice if I were always able to press Enter to leave Parachute, even when my mouse isn't hovering over a window. My expected behavior for this is the same as when clicking outside a window: the desktop is focused and its window layout remains unchanged.

When a window is focused in Parachute, the behavior would remain the same as it is currently: it leaves Parachute with that window focused. This has the issue of maybe resulting in unexpected behavior when a user switches to a desktop, fails to notice that a window is focused in Parachute, and presses Enter thinking they'll just see the desktop as it was when they left. Personally, I think that's a minor edge case given how noticeable focused windows are in Parachute.

Could this be done? This Enter key behavior is more ergonomic, matches the desktop overview effect bundled with plasma, and I think would match most users' expectations.

**Comment by tcorreabr** [comment]
To do what you have described I personally use the esc key. As I don't see any problem in using the enter key as well, I will approve your PR. Thanks!

**Comment by ikeofkc** [comment]
is it possible to close with the same key you custom bind?
