### ISSUE TITLE
Laggy KWin after installing script

### ISSUE THREAD

**Issue by Kodehawa** [tcorreabr/Parachute#68]
Seems like 0.9.0 makes KWin (lowlatency, and KWinFT) run *really* laggy after installation. It's noticeably choppy, and stuff like Yet Another Magic Lamp's animation get funky. 
This is not noticeable at 60Hz, but at 144Hz it's horrible as it makes the fps constantly jump around. 

Disabling the script fixes it all for me, so it's definitely something to do with the script. 0.8 is fine.

Is there something that runs on the background while the viewport is not active?

If you need anything just tell me. Thanks!

P.S: Great script :D

**Comment by tcorreabr** [comment]
> Seems like 0.9.0 makes KWin (lowlatency, and KWinFT) run _really_ laggy after installation. It's noticeably choppy, and stuff like Yet Another Magic Lamp's animation get funky.

Does this happen with classic KWin or only with lowlatency and KWinFT versions?

> Is there something that runs on the background while the viewport is not active?

No, this seems more like some kind of conflict on gpu access.

> If you need anything just tell me. Thanks!

Since this doesn't happen on my pc, I'll depend a lot on your help to find out what's happening. What is your distribution, cpu and gpu models?

**Comment by tcorreabr** [comment]
Can you delete (or comment) a line in the file ~/.local/share/kwin/scripts/Parachute/contents/ui/ClientComponent.qml with the content "renderTarget: KWinComponents.ThumbnailItem.FramebufferObject" and see if that solves the problem?

**Comment by Kodehawa** [comment]
> Does this happen with classic KWin or only with lowlatency and KWinFT versions?

I only really tested it with lowlatency and KWinFT. KWin uses a timer for VSync while KWinFT and KWin lowlatency try to use the GPU itself. Might be why? 

> Since this doesn't happen on my pc, I'll depend a lot on your help to find out what's happening. What is your distribution, cpu and gpu models?

Arch, Ryzen 5 2600, RX 480

> Can you delete (or comment) a line in the file ~/.local/share/kwin/scripts/Parachute/contents/ui/ClientComponent.qml with the > content "renderTarget: KWinComponents.ThumbnailItem.FramebufferObject" and see if that solves the problem?
> 
> EDIT: run kwin_x11 --replace & after editing the file.

Nope :(

[Video of the issue](https://youtu.be/uCnXvK7qMr4)

It's honestly not that noticeable in a video, but you can tell the cursor is lagging way behind the window with the script enabled, and with it disabled it works fine. For what I can tell, VSync on both KWinFT and lowlatency break, which makes it look way laggier.

**Comment by tcorreabr** [comment]
Yes, I can see the difference.

I saw that you use two monitors with different refresh rates, maybe that is the cause of the problem? I also use two monitors, but both at 60Hz.

**Comment by Kodehawa** [comment]
> I saw that you use two monitors with different refresh rates, maybe that is the cause of the problem? 

Could be. Yeah, it's 144Hz + 60Hz, that's why I use KWin lowlatency or KWinFT usually, since those actually render better with this kinda combination :)

**Comment by tcorreabr** [comment]
A test that could be done is to run the script in classic KWin, to see if the problem is related to the lowlatency or KWinFT changes.

**Comment by Kodehawa** [comment]
Maybe. The VSync mechanism on both lowlatency and KWinFT is different. I'll give it a test in a little :) 

You could test lowlatency aswell to see if it breaks for you, maybe I'm not the only one.

**Comment by tcorreabr** [comment]
I installed lowlatency and although it didn't make much sense I found the animations a little more laggier.

**Comment by Kodehawa** [comment]
KWin lowlatency really only changes how VSync works, among other minor rendering stuff (like latency controls). I wonder if something breaks GPU VSync? not sure what could break it

**Comment by tcorreabr** [comment]
Ok, can you try one more thing? Insert a line with the following content just below the line with "id: screenItem" in the file ~/.local/share/kwin/scripts/Parachute/contents/ui/ScreenComponent.qml:

`enabled: mainWindow.activated`

This will disable almost everything from Parachute when offscreen.

**Comment by Kodehawa** [comment]
Huh. Still very, very laggy. 

![image](https://user-images.githubusercontent.com/20606963/102716394-6291ba80-42ba-11eb-9b90-6c2671e62246.png)
I did it like this and ran `kwin_x11 --replace`. Seems like #72, #71 and #77 are related. I can reproduce all of them.

**Comment by Kodehawa** [comment]
Well, adding that line to 
```
    Timer {
        id: endAnimationTimer; interval: mainWindow.configAnimationsDuration; repeat: false; triggeredOnStart: 
        false;

        onTriggered: {
            animating = false;

            if (easingType === Easing.InExpo) {
                activated = false;

                // Return current big desktop to grid state. Desktops only have to be in original state for opening/closing animations.
                for (let currentScreen = 0; currentScreen < screensRepeater.count; currentScreen++)
                    screensRepeater.itemAt(currentScreen).bigDesktopsRepeater.itemAt(currentDesktop).gridView = true;

                workspace.activeClient = selectedClientItem ? selectedClientItem.client : externallySelectedClient;
            }
        }
    }
```

From main.qml fixes the issue. Well... then the script doesn't work, but that might be a lead :)

**Comment by tcorreabr** [comment]
I installed a game and I can see the fps drop now. At least it's a step to solve the problem. As soon as I fix it I should release a new version 0.9.1.

**Comment by tcorreabr** [comment]
Well, it seems that if you use `visible: mainWindow.activated` instead of `enabled: mainWindow.activated` the problem is solved. At least in case of fps drop in games (#72). As for the other issues reporting lag in KWin (this one, #71 and #77) I need feedback from you guys because they don't happen on my pc.

**Comment by Kodehawa** [comment]
That works. Yep :)

**Comment by tcorreabr** [comment]
Did this solve all the mentioned issues for you?

I already used this line in the code and it had some side effect that I don't remember now. So I'll perform some tests before releasing the new version.

**Comment by Kodehawa** [comment]
It did solve it to me, I haven't found any issues really, but who knows. 

It's weird that something harms performance _that_ much though. As in, the script uses quite a lot of resources when running. Well, and before it also did when it wasn't running :P

**Comment by Kodehawa** [comment]
With Parachute open, KWin's CPU usage goes from 1% to 50~130% (out of 1200%). Not too much, but it's still sizable. I guess it's because of thumbnail gen?

**Comment by tcorreabr** [comment]
Thumbnails, transparencies, blur, shadows of desktops and other visual effects. All this comes at a cost.

Compared to KWin Present Window and Desktop Grid effects (written in C++) for example, the fps drop when they are activated is minimal. Parachute is definitely not for old machines.

**Comment by Kodehawa** [comment]
It wasn't like this on 0.8 and it blurred, generated thumbnails, transparency and all for sure :P

0.9 is *way* slower, and uses *way* (by way I mean 100% of one core) more resources than 0.8. It's nicer, though, and with the stuff you told me to use at least it only does it when opened, so that's fine for me.

**Comment by trmdi** [comment]
Whenever I try this script, it is not laggy at first, but only after using it for a while, the lag comes. So there could be some memory leak or something like that.

**Comment by blaster9786** [comment]
> Whenever I try this script, it is not laggy at first, but only after using it for a while, the lag comes. So there could be some memory leak or something like that.

I have the same problem and I had it also on version 0.8. The lags usually start after a while and if I deactivate the parachute kwin script they stop immediately. Strange thing is that system monitor doesn't show any high CPU/RAM usage..
