### ISSUE TITLE
Window Title Colour Should Adapt To Background

### ISSUE THREAD

**Issue by Modelmat** [tcorreabr/Parachute#70]
... or alternatively, just be configurable, if that's easier

Prior to 0.9.0, on 0.8.0, the title was white. This worked with my dark background:
![image](https://user-images.githubusercontent.com/25718989/102684704-26654800-422f-11eb-849b-4d66d3ef7ff2.png)

Now, on 0.9.0, the title is now grey (default colour?). This does not work with my dark background:
![image](https://user-images.githubusercontent.com/25718989/102684754-7ba15980-422f-11eb-86ed-995f7df98a06.png)

**Comment by tcorreabr** [comment]
In version 0.8 the color of the titles was always white. In version 0.9 the color depends on the Plasma theme you are using.

As I'm using a dark theme I didn't see this happening. In the next version it should be always white again.

**Comment by Modelmat** [comment]
I'm not sure setting the default as white is a good idea - what if you have a white background, the white looks bad?
