### ISSUE TITLE
Huge perfomance impact when the script is enabled

### ISSUE THREAD

**Issue by gikari** [tcorreabr/Parachute#72]
Can't really tell where is the catch exactly, but after upgrading to 0.9.0 I noticed a huge performance impact.

**Kind of steps to reproduce:**

1. Enable script
2. Run some game (in my case it becomes laggy with varying FPS from 50 to 60)
3. Disable script
4. Game now runs smoothly with 60 FPS

My graphics processor: Mesa Intel® UHD Graphics 620. The game also uses it.

**Comment by Kodehawa** [comment]
This is probably similar to #68 

Sadly this confirms 0.9.0 has a huge performance hit. I just tested with Minecraft and the FPS absolutely tanks to hell.
