### ISSUE TITLE
Invoking the script does not do anything

### ISSUE THREAD

**Issue by DonHugo69** [tcorreabr/Parachute#73]
Similar to #26 , invoking the script via hotkey or terminal does not have any effect. Also there is no output in the terminal which could give a hint. 

This happens on Solus with 
```
Operating System: Solus 4.1
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.77.0
Qt Version: 5.15.2
Kernel Version: 5.10.1-162.current
OS Type: 64-bit
Processors: 32 × AMD Ryzen 9 3950X 16-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: Radeon RX 580 Series
```
and on openSUSE Leap 15.2 (running in a Virtualbox VM)
```
Operating System: openSUSE Leap 15.2
KDE Plasma Version: 5.18.6
KDE Frameworks Version: 5.71.0
Qt Version: 5.12.7
Kernel Version: 5.3.18-lp152.57-default
OS Type: 64-bit
Processors: 8 × AMD Ryzen 9 3950X 16-Core Processor
Memory: 7,8 GiB
```
However, the script does work Fedora 33 and openSUSE Tumbleweed (both tested in a VM). Tumbleweed and Fedora have the same or similar Qt and Plasma versions as Solus.

Installing via the KDE store or from Github with the given instructions does not make a difference. 

Restarting kwin with `kwin_x11 --replace &` only gives a small error on openSUSE eventhough I think these are not related to the problem:

```
file:///home/roland/.local/share/kwin/scripts/Parachute/contents/ui/ScreenComponent.qml:277:9: Unable to assign [undefined] to QColor
file:///home/roland/.local/share/kwin/scripts/Parachute/contents/ui/main.qml:54: TypeError: Cannot read property 'r' of undefined
file:///home/roland/.local/share/kwin/scripts/Parachute/contents/ui/main.qml:53:5: Unable to assign [undefined] to QColor
```

Is there anything I could do to get more information on what is going wrong?

**Comment by martinandersen3d** [comment]
I have the same issue on kubuntu.

I think it tries to get some of the colors from the global theme..

**Comment by DonHugo69** [comment]
A small update: 

I was curious a and tested v.0.8 and indeed, it does work on openSUSE leap 15.2. Consequently, I did a git bisect and it appears that the last working commit is 71f090f8f331f2f12532fae7ed21a36f987e1891 and from c1c3d2ff889812137424dc2b4731aec1d563ebe3 onwards it does not work.

**Comment by MrNanook** [comment]
Same issue on Manjaro KDE using hotkey or screen edges (https://store.kde.org/p/1372470/).

KDE Plasma version: 5.20.4
KDE-Frameworks version: 5.77.0
Qt version: 5.15.2
Kernel version: 5.10.1-5-MANJARO

**Comment by tcorreabr** [comment]
Thanks for the info, I'm looking for the solution.

**Comment by martinandersen3d** [comment]
some pseudocode:

myColor = rgb(1,2,3) // default fallback color

try {
myColor = someColorFromGlobalTheme
}
catch{}

**Comment by tcorreabr** [comment]
I'll insert your failsafe version for the color issue. But a user in reddit (https://www.reddit.com/r/kde/comments/kftis5/parachute_kwin_script_version_090/ggo7fzc?utm_source=share&utm_medium=web2x&context=3) fixed this temporarily and still Parachute didn't run.

**Comment by tcorreabr** [comment]
> Same issue on Manjaro KDE using hotkey or screen edges (https://store.kde.org/p/1372470/).

I am also running Manjaro in a VM. How strange is that?

**Comment by MrNanook** [comment]
> > Same issue on Manjaro KDE using hotkey or screen edges (https://store.kde.org/p/1372470/).
> 
> I am also running Manjaro in a VM. How strange is that?

I'm on the testing branch, maybe you're on stable? There's a difference in plasma versions:

[Manjaro - Branch compare](https://manjaro.org/branch-compare/):

> plasma-desktop
> repository : extra
> **Stable : 5.20.4-1   Testing : 5.20.4-2**   Unstable : 5.20.4-2
> 
> plasma-framework
> repository : extra
> **Stable : 5.76.0-1   Testing : 5.77.0-2**   Unstable : 5.77.0-2
>

**Comment by tcorreabr** [comment]
> I'm on the testing branch, maybe you're on stable? There's a difference in plasma versions (no difference in qt5-base):

No, I'm also on testing.

Have you tried to correct the color issue? I'm thinking it's two different issues here.

**Comment by MrNanook** [comment]
With `kwin_x11 --replace &` I get the following:

```
qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 429, resource id: 0, major code: 20 (GetProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 450, resource id: 0, major code: 20 (GetProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 2210, resource id: 0, major code: 20 (GetProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 2235, resource id: 0, major code: 20 (GetProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2268, resource id: 100663322, major code: 3 (GetWindowAttributes), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2280, resource id: 100663326, major code: 3 (GetWindowAttributes), minor code: 0
Cyclic dependency detected between "file:///usr/lib/qt/qml/org/kde/kirigami.2/styles/org.kde.desktop.plasma/Units.qml" and "file:///usr/lib/qt/qml/org/kde/kirigami.2/styles/org.kde.desktop.plasma/Units.qml"
qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 3539, resource id: 0, major code: 20 (GetProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 32002, resource id: 0, major code: 20 (GetProperty), minor code: 0
Job 1, 'kwin_x11 --replace &' has ended
```
So no color issues. BTW. I use the aur package.

**Comment by MrNanook** [comment]
Ok, I discovered what it was: I was using `kwinft-beta` and `kdisplay-beta`... I forgot about that. My apologies...

Switching back to `kwin` and `kscreen`, everything works fine now. :) And faster too.

Sorry for the hassle.

**Comment by MrNanook** [comment]
Ok, I discovered what it was: I was using `kwinft-beta` and `kdisplay-beta`... I forgot about that. My apologies...

Switching back to `kwin` and `kscreen`, everything works fine now. :) Thanks for the script, it's much faster here than the previous version. :)

Sorry for the hassle.

**Comment by tcorreabr** [comment]
> Ok, I discovered what it was: I was using `kwinft-beta` and `kdisplay-beta`... I forgot about that. My apologies...
> 
> Switching back to `kwin` and `kscreen`, everything works fine now. :) Thanks for the script, it's much faster here than the previous version. :)
> 
> Sorry for the hassle.

No problem.

**Comment by tcorreabr** [comment]
For those who still can't run the script, can you see if the milou package is installed? This is a dependency of version 0.9 that didn't exist in 0.8.

**Comment by martinandersen3d** [comment]
milou package - how to install?

**Comment by tcorreabr** [comment]
Using the package manager of your distribution. For example, `pacman -S milou` for Arch based distro.

**Comment by daviddoc** [comment]
Same here, kubuntu 20.10. I checked and milou is already installed.
Tried qdbus org.kde.kglobalaccel /component/kwin invokeShortcut Parachute in terminal, nothing happens.
Tried installing through command line, and through kde store (purging all parachute related files between installs).
